modLoader = "javafml"
loaderVersion = "[47,)"
license = "Apache-2.0"

[[mods]]
modId = "jiushi_admin"
version = "1.0.11-alpha"
displayName = "[九氏]游戏内面板"
authors = "MA"
description = '''[九氏]游戏内管理面板
功能: 管理员分级(服主/OP) · 邀请码验证 · 广播与定时公告 · 金币系统 · 玩家商店 · 传送点与TPA · 踢出/封禁 · 兑换券 · DLC扩展支持'''

[[dependencies.jiushi_admin]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,48)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.jiushi_admin]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2]"
    ordering = "NONE"
    side = "BOTH"
